import type { Metadata } from "next";
import "@/styles/main.css";

export const metadata: Metadata = {
  title: "Rohit Kushwaha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-950">{children}</body>
    </html>
  );
}
